### ISSUE TITLE
install not working in frappe custom app

### ISSUE THREAD

**Issue by saru2020** [frappe/frappe-ui#186]
i'm trying to install `frappe-ui (0.1.69)` in a custom frappe app's webpage by following [these steps](https://greycube.in/blog/customisation/add-external-javascript-library-in-web-page-and-desk-a-comprehensive-guide) but it doesn't work
note: the other js libraries mentioned in the linked blog are working fine

this is my `library.bundle.js` file inside `/public/js/`:
<img width="787" alt="Screenshot 2024-09-17 at 12 25 30 AM" src="https://github.com/user-attachments/assets/8783c0af-5589-43fb-bbe1-49cf044f34cc">

error logs when I try to build my app using `bench build --app my_custom_app`

```
$ node esbuild --apps my_custom_app --run-build-command
▲ [WARNING] "import.meta" is not available in the configured target environment ("es2017") and will be empty [empty-import-meta]

    ../my_custom_app/node_modules/frappe-ui/src/utils/socketio.js:5:17:
      5 │   let siteName = import.meta.env.DEV ? host : window.site_name
        ╵                  ~~~~~~~~~~~

✘ [ERROR] [plugin vue] Error parsing JavaScript expression: Unexpected token, expected "," (1:16)

    ../my_custom_app/node_modules/frappe-ui/src/components/Tree/Tree.vue:47:24:
      47 │ child[nodeKey] as string
         ╵                         ^

  The plugin "vue" was triggered by this import

    ../my_custom_app/node_modules/frappe-ui/src/components/Tree/Tree.vue:1:160:
      1 │ ...ort { render } from "/workspace/development/frappe-bench/apps/my_custom_app/node_modules/frappe-ui/src/components...
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] [plugin vue] Error parsing JavaScript expression: Unexpected token, expected "," (3:47)

    ../my_custom_app/node_modules/frappe-ui/src/components/Checkbox.vue:20:0:
      20 │ 
         ╵ ^

        (e) =>
          $emit('update:modelValue', (e.target as HTMLInputElement).checked)
      

  The plugin "vue" was triggered by this import

    ../my_custom_app/node_modules/frappe-ui/src/components/Checkbox.vue:1:159:
      1 │ ...ort { render } from "/workspace/development/frappe-bench/apps/my_custom_app/node_modules/frappe-ui/src/components...
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] [plugin vue] Missing template

    node_modules/esbuild-plugin-vue3/dist/index.js:291:54:
      291 │                                                 throw new Error("Missing template");
          ╵                                                       ^

    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:291:55
    at step (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:67:23)
    at Object.next (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:48:53)
    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:42:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:38:12)
    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:284:172
    at AsyncCache.get (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/utils.js:129:20)
    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:284:118
    at callback (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:993:34)

  This error came from the "onLoad" callback registered here:

    node_modules/esbuild-plugin-vue3/dist/index.js:284:34:
      284 │                             build.onLoad({ filter: /.*/, namespace: "sfc-template" }, function (args) { return ...
          ╵                                   ~~~~~~

    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:284:35
    at step (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:67:23)
    at Object.next (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:48:53)
    at fulfilled (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:39:58)

  The plugin "vue" was triggered by this import

    ../my_custom_app/node_modules/frappe-ui/src/components/Resource.vue:1:159:
      1 │ ...ort { render } from "/workspace/development/frappe-bench/apps/my_custom_app/node_modules/frappe-ui/src/components...
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] [plugin vue] Missing template

    node_modules/esbuild-plugin-vue3/dist/index.js:291:54:
      291 │                                                 throw new Error("Missing template");
          ╵                                                       ^

    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:291:55
    at step (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:67:23)
    at Object.next (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:48:53)
    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:42:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:38:12)
    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:284:172
    at AsyncCache.get (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/utils.js:129:20)
    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:284:118
    at callback (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:993:34)

  This error came from the "onLoad" callback registered here:

    node_modules/esbuild-plugin-vue3/dist/index.js:284:34:
      284 │                             build.onLoad({ filter: /.*/, namespace: "sfc-template" }, function (args) { return ...
          ╵                                   ~~~~~~

    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:284:35
    at step (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:67:23)
    at Object.next (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:48:53)
    at fulfilled (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild-plugin-vue3/dist/index.js:39:58)

  The plugin "vue" was triggered by this import

    ../my_custom_app/node_modules/frappe-ui/src/components/FeatherIcon.vue:1:162:
      1 │ ...ort { render } from "/workspace/development/frappe-bench/apps/my_custom_app/node_modules/frappe-ui/src/components...
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] [plugin frappe-vue-style] Cannot read properties of undefined (reading 'outputs')

    /workspace/development/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:10:41:
      10 │       let files = get_files(result.metafile.outputs);
         ╵                                             ^

    at /workspace/development/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:10:42
    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1052:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  This error came from the "onEnd" callback registered here:

    /workspace/development/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:9:8:
      9 │     build.onEnd((result) => {
        ╵           ~~~~~

    at setup (/workspace/development/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:9:9)
    at handlePlugins (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:855:23)

 ERROR  There were some problems during build

Error: Build failed with 5 errors:
../my_custom_app/node_modules/frappe-ui/src/components/Checkbox.vue:20:16: ERROR: [plugin: vue] Error parsing JavaScript expression: Unexpected token, expected "," (3:47)
../my_custom_app/node_modules/frappe-ui/src/components/Tree/Tree.vue:47:48: ERROR: [plugin: vue] Error parsing JavaScript expression: Unexpected token, expected "," (1:16)
node_modules/esbuild-plugin-vue3/dist/index.js:291:54: ERROR: [plugin: vue] Missing template
node_modules/esbuild-plugin-vue3/dist/index.js:291:54: ERROR: [plugin: vue] Missing template
/workspace/development/frappe-bench/apps/frappe/esbuild/frappe-vue-style.js:10:41: ERROR: [plugin: frappe-vue-style] Cannot read properties of undefined (reading 'outputs')
    at failureErrorWithLog (/workspace/development/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1624:15)
    at /workspace/development/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1266:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Done in 3.49s.
``` 

I don't want to use `frappe-ui-starter`, whats the alternative route to bundle `frappe-ui`?
what are all the ways for non-ES6 integrations?

any inputs would be helpful, TIA!

**Comment by saru2020** [comment]
[this](https://www.youtube.com/live/3xpfw4qrzM0?t=1180s) is the only best way to do custom apps, I believe
