### ISSUE TITLE
Resource component causing crash

### ISSUE THREAD

**Issue by this-gavagai** [frappe/frappe-ui#40]
Hello,

I am encountering a build failure when attempting to use the Resource component. Using exactly the code displayed here:
https://frappeui.com/components/resource.html

I get the following error:
```
[Vue warn]: Property "$resources" was accessed during render but is not defined on instance.                                                            15:22:29
[Vue warn]: Unhandled error during execution of render function                                                                                         15:22:29
  at <Resource options= { url: 'https://jsonplaceholder.typicode.com/users/1' } >
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'resource')                                                  15:22:29
    at Proxy.render (/Users/petergraif/Sites/oi2/node_modules/frappe-ui/src/components/Resource.vue:12:33)
    at renderComponentRoot (/Users/petergraif/Sites/oi2/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:891:44)
    at renderComponentSubTree (/Users/petergraif/Sites/oi2/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:51)
    at renderComponentVNode (/Users/petergraif/Sites/oi2/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (/Users/petergraif/Sites/oi2/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:624:12)
    at _sfc_ssrRender (/Users/petergraif/Sites/oi2/pages/index2.vue:22:31)
    at renderComponentSubTree (/Users/petergraif/Sites/oi2/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:254:17)
    at renderComponentVNode (/Users/petergraif/Sites/oi2/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (/Users/petergraif/Sites/oi2/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:299:22)
    at renderComponentSubTree (/Users/petergraif/Sites/oi2/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)
```

**Comment by netchampfaris** [comment]
You are trying to access `$resources` in your code somewhere. In the documentation example there are no `$resources`. It is used only in Options API. I need to see more of your code to help you, but most likely this is not a frappe-ui issue.

**Comment by this-gavagai** [comment]
Unfortunately, this project went another direction, and I don't have the ability to test anymore. I'm quite certain I wasn't calling $resources in my own code, thought it's possible that it was getting called indirectly somehow. I'll close for now and open another issue if I can reproduce the problem with live code.
